# Generated by Django 4.2.4 on 2023-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
