# Generated by Django 4.2.4 on 2023-08-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.student_information'),
        ),
    ]
